version: 2
jobs:
  build:
    working_directory: ~/cross-browser-testing
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: "export APPLITOOLS_BATCH_ID=`echo $CIRCLE_SHA1`"
      - run: # run tests
          name: Run Cypress/Applitools tests
          command: npm run cy:run -- --spec "cypress/integration/salesforce-contactus.spec.js"
